services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "8081:8081"
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./node_modules:/app/node_modules
      - ./apps/backend/node_modules:/app/apps/backend/node_modules
    networks:
      - leopple-games-network

  login-screen:
    build:
      context: .
      dockerfile: apps/login-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/login-screen:/app/apps/login-screen
    networks:
      - leopple-games-network

  games-list-screen:
    build:
      context: .
      dockerfile: apps/games-list-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3001:3001"
    volumes:
      - ./apps/games-list-screen:/app/apps/games-list-screen
    networks:
      - leopple-games-network

networks:
  leopple-games-network: