services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "8081:8081"
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./node_modules:/app/node_modules
      - ./apps/backend/node_modules:/app/apps/backend/node_modules
    depends_on:
      - postgresql
      - redis
    networks:
      - leopple-games-network


  login-screen:
    build:
      context: .
      dockerfile: apps/login-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/login-screen:/app/apps/login-screen
    networks:
      - leopple-games-network


  games-list-screen:
    build:
      context: .
      dockerfile: apps/games-list-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3001:3001"
    volumes:
      - ./apps/games-list-screen:/app/apps/games-list-screen
    networks:
      - leopple-games-network


  configuration-screen:
    build:
      context: .
      dockerfile: apps/config-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3003:3003"
    volumes:
      - ./apps/config-screen:/app/apps/config-screen
    networks:
      - leopple-games-network


  details-game-screen:
    build:
      context: .
      dockerfile: apps/details-game-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3004:3004"
    volumes:
      - ./apps/details-game-screen:/app/apps/details-game-screen
    networks:
      - leopple-games-network

  
  my-games-screen:
    build:
      context: .
      dockerfile: apps/my-games-screen/Dockerfile
    command:
      - npm
      - run
      - dev
    ports:
      - "3002:3002"
    volumes:
      - ./apps/my-games-screen:/app/apps/my-games-screen
    networks:
      - leopple-games-network

  
  postgresql:
    image: postgres:18
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=leopple-games
    ports:
      - "5432:5432"
    volumes:
      - polls_pg_data:/var/lib/postgresql
    networks:
      - leopple-games-network
  
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - polls_redis_data:/data
    networks:
      - leopple-games-network

volumes:
  polls_pg_data:
  polls_redis_data:

networks:
  leopple-games-network: